[project]
name = "telegram-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.3",
    "pandas>=2.2.3",
    "polars>=1.16.0",
    "seaborn>=0.13.2",
]
